Repository DeepDive-Final-Project/backend, pull requests merged in 2025-03, with the labels that each got.

#16 [#15] 마이페이지를 관리 기능 구현
  src/main/java/com/goorm/team9/icontact/IContactApplication.java
  src/main/java/com/goorm/team9/icontact/common/error/ClientErrorCode.java
  src/main/java/com/goorm/team9/icontact/common/error/ErrorCodeInterface.java
  src/main/java/com/goorm/team9/icontact/common/exception/CustomException.java
  src/main/java/com/goorm/team9/icontact/common/exception/ErrorResponse.java
  src/main/java/com/goorm/team9/icontact/common/exception/GlobalExceptionHandler.java
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/EnumController.java
  src/main/java/com/goorm/team9/icontact/domain/client/converter/ClientConverter.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/ClientRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/TopicEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Career.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Framework.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Industry.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Interest.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Language.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Role.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Status.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ImageFileStorageService.java
  src/main/java/com/goorm/team9/icontact/domain/common/BaseTimeEntity.java
  src/main/java/com/goorm/team9/icontact/domain/common/EnumWithDescription.java
Labels: feature

#14 [#7] feat: 실시간 채팅 기능
  build.gradle
  src/main/java/com/goorm/team9/icontact/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/chat/dto/ChatMessageDto.java
  src/main/java/com/goorm/team9/icontact/chat/dto/ChatRoomRequest.java
  src/main/java/com/goorm/team9/icontact/chat/dto/ChatRoomResponse.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatMessageType.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatRoom.java
  src/main/java/com/goorm/team9/icontact/chat/repository/ChatMessageRepository.java
  src/main/java/com/goorm/team9/icontact/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/chat/service/ChatRoomService.java
  src/main/java/com/goorm/team9/icontact/chat/service/WebSocketSessionService.java
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/config/websocket/WebSocketConfig.java
  src/main/java/com/goorm/team9/icontact/config/websocket/WebSocketHandler.java
  src/main/java/com/goorm/team9/icontact/config/websocket/WebSocketHandshakeInterceptor.java
  src/test/java/com/goorm/team9/icontact/chat/controller/ChatMessageControllerTest.java
  src/test/java/com/goorm/team9/icontact/chat/service/ChatMessageServiceTest.java
  src/test/java/com/goorm/team9/icontact/websocket/WebSocketSessionServiceTest.java
Labels: feature, test

#19 fix: chatRoomId -> roomId 변수명 통일
  src/main/java/com/goorm/team9/icontact/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/chat/dto/ChatMessageDto.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/chat/service/ChatRoomService.java
  src/main/java/com/goorm/team9/icontact/chat/service/WebSocketSessionService.java
  src/main/java/com/goorm/team9/icontact/config/websocket/WebSocketHandler.java
  src/main/java/com/goorm/team9/icontact/config/websocket/WebSocketHandshakeInterceptor.java
Labels: fix

#20 [#9] feat: 소셜 로그인 (깃허브)
  build.gradle
  docker-compose.yml
  src/main/java/com/goorm/team9/icontact/sociallogin/config/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Career.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Industry.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/LoginHistory.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/OAuth.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Provider.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Role.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Status.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/User.java
  src/main/java/com/goorm/team9/icontact/sociallogin/dto/JwtResponse.java
  src/main/java/com/goorm/team9/icontact/sociallogin/dto/OAuthLoginRequest.java
  src/main/java/com/goorm/team9/icontact/sociallogin/repository/LoginHistoryRepository.java
  src/main/java/com/goorm/team9/icontact/sociallogin/repository/OAuthRepository.java
  src/main/java/com/goorm/team9/icontact/sociallogin/repository/UserRepository.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtBlacklist.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtLogoutSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtTokenProvider.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtUtil.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/provider/GitHubOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/sociallogin/service/GithubLoginStrategy.java
  src/main/java/com/goorm/team9/icontact/sociallogin/service/OAuthService.java
  src/main/java/com/goorm/team9/icontact/sociallogin/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature

#23 [#21] 병합 충돌 해결 후 리펙토링
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/domain/LoginHistory.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/domain/OAuth.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/dto/JwtResponse.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/dto/OAuthLoginRequest.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/LoginHistoryRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/OAuthRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtBlacklist.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtLogoutSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtTokenProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtUtil.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GitHubOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/GithubLoginStrategy.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/UserService.java
  src/main/java/com/goorm/team9/icontact/sociallogin/config/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Career.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Industry.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Provider.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Role.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/Status.java
  src/main/java/com/goorm/team9/icontact/sociallogin/domain/User.java
  src/main/java/com/goorm/team9/icontact/sociallogin/repository/UserRepository.java
  src/main/java/com/goorm/team9/icontact/sociallogin/security/jwt/JwtUtil.java
  src/main/resources/application.yml
Labels: refactor

#22 [#22] Feature/location data
  build.gradle
  src/main/java/com/goorm/team9/icontact/api/location/controller/LocationController.java
  src/main/java/com/goorm/team9/icontact/api/location/dto/LocationRequest.java
  src/main/java/com/goorm/team9/icontact/api/location/dto/LocationResponse.java
  src/main/java/com/goorm/team9/icontact/api/location/service/LocationService.java
  src/main/java/com/goorm/team9/icontact/common/exception/GlobalExceptionErrorCode.java
  src/main/java/com/goorm/team9/icontact/config/redis/RedisConfig.java
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Language.java
Labels: feature

#27 [#17] 열거형 분기화 및 기타 작업
  .github/workflows/CICD.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/goorm/team9/icontact/common/error/ClientErrorCode.java
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/EnumController.java
  src/main/java/com/goorm/team9/icontact/domain/client/converter/ClientConverter.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/ClientRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Career.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Industry.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Interest.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Role.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/Status.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ImageFileStorageService.java
  src/main/resources/application.yml
  src/test/java/com/goorm/team9/icontact/chat/service/ChatMessageServiceTest.java
  uploads/profile-images/default_profile_image.jpg
Labels: feature, fix

#29 [#26] fix: 소셜 로그인 오류 수정
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtBlacklist.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtLogoutSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GitHubOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GoogleOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/KakaoOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/OAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/OAuthProviderFactory.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: fix

#30 [#18] 채팅방 개설 관리 기능 구현
  src/main/java/com/goorm/team9/icontact/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/chat/dto/ChatMessageDto.java
  src/main/java/com/goorm/team9/icontact/chat/dto/ChatRoomResponse.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatJoin.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatRequest.java
  src/main/java/com/goorm/team9/icontact/chat/entity/ChatRoom.java
  src/main/java/com/goorm/team9/icontact/chat/entity/RequestStatus.java
  src/main/java/com/goorm/team9/icontact/chat/repository/ChatJoinRepository.java
  src/main/java/com/goorm/team9/icontact/chat/repository/ChatMessageRepository.java
  src/main/java/com/goorm/team9/icontact/chat/repository/ChatRequestRepository.java
  src/main/java/com/goorm/team9/icontact/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/chat/service/ChatRoomService.java
  src/main/java/com/goorm/team9/icontact/chat/service/WebSocketSessionService.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
Labels: feature, fix

#33 [#28] Fix/profile and setting
  src/main/java/com/goorm/team9/icontact/common/error/ClientErrorCode.java
  src/main/java/com/goorm/team9/icontact/common/error/MemoErrorCode.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/MemoController.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MemoRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/MemoResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/MemoEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/MemoRepository.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ImageFileStorageService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/MemoService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
Labels: feature, fix

#39 [#37] Add Monitoring Setting
  build.gradle
  src/main/resources/application.yml
Labels: feature

#40 [#39] 모니터링 설정 및 구조 재조정
  .github/workflows/CICD.yml
  build.gradle
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/config/swagger/SwaggerConfig.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/entity/LoginHistory.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/entity/OAuth.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/LoginHistoryRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/OAuthRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feature, fix

#41 [#31] feat: 소셜 로그인 : 구글 & 카카오
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GitHubOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GoogleOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/KakaoOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/OAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/OAuthProviderFactory.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
  src/main/resources/application.yml
Labels: feature, fix

#44 [#32] 사용자 차단 기능 구현
  src/main/java/com/goorm/team9/icontact/domain/block/controller/BlockController.java
  src/main/java/com/goorm/team9/icontact/domain/block/entity/Block.java
  src/main/java/com/goorm/team9/icontact/domain/block/repository/BlockRepository.java
  src/main/java/com/goorm/team9/icontact/domain/block/service/BlockService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatJoinRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: feature

#47 [#46] 채팅방 개수 제한 삭제
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: refactor

#48 [#45] Client 관련 코드 리펙토링
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/converter/ClientConverter.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
Labels: refactor

#50 [#43] 주변 참가자 조회 리팩토링
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: refactor

#52 [#49] fix: 소셜 로그인 : 구글 & 카카오
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/dto/OAuthTokenResponse.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtTokenProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GitHubOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/GoogleOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/KakaoOAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/provider/OAuthProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
  src/main/resources/application.yml
Labels: feature, fix

#54 [#51] 컨퍼런스와 강연 내용을 관리하는 기능 구현
  src/main/java/com/goorm/team9/icontact/common/error/LectureErrorCode.java
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/config/swagger/SwaggerConfig.java
  src/main/java/com/goorm/team9/icontact/domain/conference/controller/ConferenceController.java
  src/main/java/com/goorm/team9/icontact/domain/conference/dto/request/ConferenceRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/conference/dto/response/ConferenceResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/conference/entity/ConferenceEntity.java
  src/main/java/com/goorm/team9/icontact/domain/conference/enums/Day.java
  src/main/java/com/goorm/team9/icontact/domain/conference/repository/ConferenceRepository.java
  src/main/java/com/goorm/team9/icontact/domain/conference/service/ConferenceService.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/controller/LectureController.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/dto/request/LectureRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/dto/response/LectureResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/entity/LectureEntity.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/repository/LectureRepository.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/service/LectureService.java
Labels: feature, fix

#58 [#57] 채팅 api 수정 및 에러 해결
  src/main/java/com/goorm/team9/icontact/domain/block/controller/BlockController.java
  src/main/java/com/goorm/team9/icontact/domain/block/dto/BlockRequestDto.java
  src/main/java/com/goorm/team9/icontact/domain/block/dto/UnblockRequesetDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatRequest.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatJoinRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRequestRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: feature, fix, refactor

#61 [refactor] 요청 타입 변경 및 CORS 설정 수정
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/MemoController.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/ClientRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageCreateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageUpdateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/conference/controller/ConferenceController.java
  src/main/java/com/goorm/team9/icontact/domain/conference/dto/request/ConferenceRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/controller/LectureController.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/dto/request/LectureRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/lecture/dto/response/LectureResponseDTO.java
Labels: fix, refactor

#62 [#60] feat: S3 연결
  build.gradle
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ImageFileStorageService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/S3ImageStorageService.java
  src/main/java/com/goorm/team9/icontact/domain/conference/entity/ConferenceEntity.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature, fix

#68 [#64] fix: 요청 데이터 형식 변경
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
Labels: fix

#67 [feat] 채팅방 정렬 추가
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: feature

#72 [#71] 등록된 모든 사용자를 출력하는 기능 추가
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
Labels: feature

#73 [#56] 위치 저장 및 탐색 로직 리팩토링 & 관심분야 검증 개선
  src/main/java/com/goorm/team9/icontact/common/exception/GlobalExceptionErrorCode.java
  src/main/java/com/goorm/team9/icontact/domain/location/controller/LocationController.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/LocationResponse.java
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: feature, fix, refactor

#75 [#70] 읽지 않은 메시지 개수 표시
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatJoin.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatJoinRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: feature, refactor

#76 [#73] 최초 위치 데이터 저장 검증 및 관심분야 갱신
  src/main/java/com/goorm/team9/icontact/common/exception/GlobalExceptionErrorCode.java
  src/main/java/com/goorm/team9/icontact/domain/location/controller/LocationController.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/LocationResponse.java
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: refactor

#80 [#78] 위치 데이터 저장 및 조회 기능 개선, Role/Career 필터링 추가
  src/main/java/com/goorm/team9/icontact/common/exception/GlobalExceptionErrorCode.java
  src/main/java/com/goorm/team9/icontact/domain/location/controller/LocationController.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/LocationResponse.java
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: feature, refactor

#81 [#77] 채팅방 요청 필터링 구현
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRequestController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestCountDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatJoinRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRequestRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRequestService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: feature, refactor

#83 [#82] 채팅 관련 리팩토링
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRequestController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatMessageDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatRequest.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatRoom.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRequestRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRequestService.java
Labels: feature, refactor

#85 [#84] 채팅 dto 리팩토링
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestDto.java
Labels: refactor

#87 [#66] 온라인 알림 전송
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatMessageNotificationDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestNotificationDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRequestService.java
Labels: feature

#79 [#69] refactor: 소셜 로그인 업데이트
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatMessage.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/dto/LoginUserResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/dto/OAuthLoginResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/entity/OAuth.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/OAuthRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/exception/GlobalExceptionHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/exception/OAuthTokenExpiredException.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtBlacklist.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/NicknameGeneratorService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
  src/main/resources/application.yml
Labels: fix, refactor

#91 [#90] refactor : 소셜 로그인 업데이트
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/LoginHistoryRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/repository/OAuthRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
Labels: refactor

#94 [#93] fix: 소셜 로그인 수정
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientSaveService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
Labels: fix, refactor

#96 [#93] fix: 소셜 로그인 수정
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: fix

#99 [#98] Redis 저장 TTL 변경 및 API 문서화 예시(example) 값 업데이트
  src/main/java/com/goorm/team9/icontact/domain/location/dto/DeleteRequest.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/LocationRequest.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/LocationResponse.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/NearbyRequest.java
  src/main/java/com/goorm/team9/icontact/domain/location/dto/RefreshRequest.java
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: feature

#102 [#101] 요청시 이미지 반환해주는 API 구현
  src/main/java/com/goorm/team9/icontact/domain/client/controller/ClientController.java
  src/main/java/com/goorm/team9/icontact/domain/client/converter/ClientConverter.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientProfileImageDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/S3ImageStorageService.java
Labels: feature, refactor

#105 [#100] 채팅 리팩토링
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRequestService.java
Labels: fix

#106 [#93] fix: 소셜 로그인 수정
  src/main/java/com/goorm/team9/icontact/config/security/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/goorm/team9/icontact/config/security/OAuth2Config.java
  src/main/java/com/goorm/team9/icontact/config/security/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feature, fix

#108 [#107] 위치 탐색 반경 기본값을 10m에서 50m로 수정
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: refactor

#109 [#93] fix: 소셜 로그인 수정
  src/main/java/com/goorm/team9/icontact/config/security/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/goorm/team9/icontact/config/security/OAuth2Config.java
  src/main/java/com/goorm/team9/icontact/domain/client/repository/ClientRepository.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/controller/AuthController.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtAuthenticationSuccessHandler.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/security/jwt/JwtTokenProvider.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/AuthService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: fix

#110 [#107] 위치 탐색 반경 기본값을 50m에서 10m로 수정
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: refactor

#111 [#104] 테스트 코드 작성 및 관심사 API 수정
  src/main/java/com/goorm/team9/icontact/IContactApplication.java
  src/main/java/com/goorm/team9/icontact/common/error/ClientErrorCode.java
  src/main/java/com/goorm/team9/icontact/config/jpa/JpaConfig.java
  src/main/java/com/goorm/team9/icontact/domain/client/controller/EnumController.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageCreateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageUpdateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientProfileImageDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/enums/InterestCategory.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientEnumService.java
  src/test/java/com/goorm/team9/icontact/client/ClientControllerTest.java
  src/test/java/com/goorm/team9/icontact/client/ClientServiceTest.java
Labels: feature, test, fix, refactor

#113 [#114] LocationController 테스트 작성 및 필터링 조건 검증 케이스 추가
  src/test/java/com/goorm/team9/icontact/location/LocationControllerTest.java
Labels: test

#117 [#116] 반환 정보 추가 제공: 참가자 닉네임, 소개
  src/main/java/com/goorm/team9/icontact/domain/location/dto/LocationResponse.java
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: feature

#115 [#95] 채팅 테스트 코드 작성
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatMessageService.java
  src/test/java/com/goorm/team9/icontact/chat/service/ChatMessageServiceTest.java
  src/test/java/com/goorm/team9/icontact/chat/service/ChatRequestServiceTest.java
  src/test/java/com/goorm/team9/icontact/chat/service/ChatRoomServiceTest.java
  src/test/java/com/goorm/team9/icontact/chat/service/EmailServiceTest.java
  src/test/java/com/goorm/team9/icontact/websocket/WebSocketHandlerTest.java
  src/test/java/com/goorm/team9/icontact/websocket/WebSocketSessionServiceTest.java
Labels: test

#119 [#118] 닉네임 필드명 nickname → nick_name으로 수정하여 SQL 조회 오류 해결
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: bug, fix

#121 [#120] 위치 탐색 테스트 코드 수정
  src/test/java/com/goorm/team9/icontact/location/LocationControllerTest.java
Labels: test, fix

#123 [#122] 채팅방 나간 사용자에는 채팅방 목록에서 제외되도록 필터링 추가
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: feature

#126 [#125] link컬럼 리스트화
  src/main/java/com/goorm/team9/icontact/domain/client/converter/ClientConverter.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageCreateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageUpdateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientLinkEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/test/java/com/goorm/team9/icontact/client/ClientServiceTest.java
Labels: feature, refactor

#127 [#124] 채팅 리팩토링 및 테스트 코드 작성
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRequestDto.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRoomRequest.java
  src/main/java/com/goorm/team9/icontact/domain/chat/dto/ChatRoomResponse.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRequestRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRequestService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
  src/test/java/com/goorm/team9/icontact/chat/controller/ChatMessageControllerTest.java
  src/test/java/com/goorm/team9/icontact/chat/controller/ChatRequestControllerTest.java
  src/test/java/com/goorm/team9/icontact/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/goorm/team9/icontact/chat/service/ChatRequestServiceTest.java
  src/test/java/com/goorm/team9/icontact/websocket/WebSocketSessionServiceTest.java
Labels: feature, test, refactor

#131 [#130] Redis TTL 임시 비활성화
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: feature

#132 [#128] 채팅방 나가기 기능 관련 수정
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatMessageController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/controller/ChatRoomController.java
  src/main/java/com/goorm/team9/icontact/domain/chat/entity/ChatRoom.java
  src/main/java/com/goorm/team9/icontact/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatMessageService.java
  src/main/java/com/goorm/team9/icontact/domain/chat/service/ChatRoomService.java
Labels: fix, refactor

#133 [#129] Client필드 변경에 따른 코드 수정
  src/main/java/com/goorm/team9/icontact/domain/client/controller/EnumController.java
  src/main/java/com/goorm/team9/icontact/domain/client/converter/ClientConverter.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/ClientLinkRequestDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageCreateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/request/MyPageUpdateRequest.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientLinkResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/dto/response/ClientResponseDTO.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/ClientLinkEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/entity/TopicEntity.java
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/team9/icontact/domain/sociallogin/service/OAuthService.java
  src/test/java/com/goorm/team9/icontact/client/ClientControllerTest.java
  src/test/java/com/goorm/team9/icontact/client/ClientServiceTest.java
Labels: feature, fix, refactor

#135 [#134] 근처 참가자 응답에 role, career 필드 반환 수정
  src/main/java/com/goorm/team9/icontact/domain/location/service/LocationService.java
Labels: feature

#137 [#136] 프로필 수정 시 client_link, it_topic 테이블의 존재 유무를 검증하는 로직 추가
  src/main/java/com/goorm/team9/icontact/domain/client/service/ClientService.java
Labels: feature, fix
